#!/usr/bin/env python3
"""Author MASSIVE per-tier training sets (no API). Strategy:

  VERBATIM (the backbone, used by every tier) is generated by REVERSE CORRUPTION:
  author a clean, well-formed sentence, then programmatically "dirty" it into
  realistic raw dictation (lowercase, strip punctuation + apostrophes, inject only
  the REMOVABLE disfluencies um/uh/er/hmm/like-tic/you-know-tic + stutters). The
  clean sentence IS the verbatim target -> guaranteed-correct pairs at scale.
  Templates with slot pools give combinatorial diversity.

  TIDY and FORMATTED are authored as (verbose/raw -> tidied) and
  (enumeration/multi-topic -> structured) pairs, plus the existing Grok-made data.

Writes three tier files (each a single .jsonl, filled to the brim):
  data/train_0.8b.jsonl  -> verbatim only
  data/train_2b.jsonl    -> verbatim + tidy            (OVERWRITES the old 1245 set)
  data/train_4b.jsonl    -> verbatim + tidy + formatted
"""
from __future__ import annotations
import json, random, re, sys
from pathlib import Path
sys.path.insert(0, str(Path(__file__).resolve().parent))
sys.path.insert(0, str(Path(__file__).resolve().parent.parent))
from build_dataset import WRAP, cleanup_prompt

RNG = random.Random(42)   # reproducible
HERE = Path(__file__).resolve().parent

# ---------------------------------------------------------------- corruption
_REMOVABLE = ["um", "uh", "er", "hmm", "like", "you know"]   # ONLY disfluencies verbatim removes
def corrupt(clean: str) -> str:
    """Clean, well-formed sentence -> realistic raw STT (lowercase, no punct/
    apostrophes, injected removable disfluencies + occasional stutter)."""
    t = clean.lower().replace("’", "'")
    t = re.sub(r"[.,!?;:\"()\[\]]", " ", t)
    t = t.replace("'", "")                  # cant, im, lets, thats ...
    t = re.sub(r"\s+", " ", t).strip()
    words = t.split()
    out: list[str] = []
    if RNG.random() < 0.55:                 # sometimes a leading filler
        out.append(RNG.choice(["um", "uh", "so um", "uh like", "okay um", "yeah um"][:4] + ["um", "uh"]))
    for w in words:
        if RNG.random() < 0.06:             # mid filler (tic)
            out.append(RNG.choice(_REMOVABLE))
        out.append(w)
        if RNG.random() < 0.025:            # stutter
            out.append(w)
    return " ".join(out)

def verbatim_pairs(cleans, per=2):
    """Each clean sentence -> `per` distinct corruptions (deduped)."""
    pairs = []
    for c in cleans:
        seen = set()
        tries = 0
        while len(seen) < per and tries < per * 4:
            tries += 1
            r = corrupt(c)
            if r and r not in seen:
                seen.add(r); pairs.append((r, c, "verbatim"))
    return pairs

# ------------------------------------------------- clean-sentence templates
def fill(templates, **pools):
    """Expand each template over random slot combos, capped per template."""
    out = []
    for tmpl, cap in templates:
        slots = re.findall(r"\{(\w+)\}", tmpl)
        seen = set()
        tries = 0
        while len(seen) < cap and tries < cap * 6:
            tries += 1
            vals = {s: RNG.choice(pools[s]) for s in slots}
            s = tmpl.format(**vals)
            if s not in seen:
                seen.add(s); out.append(s)
    return out

PEOPLE = ["Sarah", "Michael", "Priya", "David", "Amanda", "Raj", "Carlos", "Fatima",
          "Jessica", "Tom", "Elena", "Marcus", "Nina", "Omar", "Grace", "Leo"]
PLACES = ["San Francisco", "London", "the office", "the station", "the cafe", "Tokyo",
          "the warehouse", "Berlin", "the lobby", "downtown", "the airport", "Austin"]
DAYS = ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "the weekend",
        "tomorrow", "next week", "the first", "the 15th"]
THINGS = ["report", "invoice", "proposal", "contract", "deck", "budget", "email",
          "spreadsheet", "design", "schedule", "agenda", "draft", "summary", "ticket"]
VERBS = ["send", "review", "finish", "update", "forward", "approve", "share", "check"]
COMPANIES = ["Google", "Netflix", "Amazon", "Spotify", "Slack", "Notion", "Tesla", "Apple"]
TECH = [("use effect", "useEffect"), ("use state", "useState"), ("get user data", "getUserData"),
        ("api", "API"), ("json", "JSON"), ("css", "CSS"), ("html", "HTML"), ("sql", "SQL"),
        ("git hub", "GitHub"), ("type script", "TypeScript"), ("java script", "JavaScript")]
FEELINGS = ["excited", "nervous", "optimistic", "worried", "thrilled", "relieved"]

# Each (template, cap). Slots filled from pools above. Clean = well-formed target.
TEMPL = [
    ("Can you {VERBS} the {THINGS} by {DAYS}?", 40),
    ("Please {VERBS} the {THINGS} before {DAYS}.", 35),
    ("I'll {VERBS} the {THINGS} first thing {DAYS}.", 35),
    ("Let's meet {PEOPLE} at {PLACES} on {DAYS}.", 40),
    ("We're flying into {PLACES} on {DAYS}.", 30),
    ("I talked to {PEOPLE} about the {THINGS}.", 35),
    ("The {THINGS} is ready for review.", 14),
    ("I'm {FEELINGS} about the {THINGS}.", 30),
    ("Thanks {PEOPLE}, the {THINGS} really helped.", 30),
    ("{PEOPLE} from {COMPANIES} is joining the call.", 35),
    ("Did {PEOPLE} ever send over the {THINGS}?", 35),
    ("What time does the meeting about the {THINGS} start?", 14),
    ("Forward the {THINGS} to {PEOPLE} when you can.", 35),
    ("We use {COMPANIES} and {COMPANIES} for everything.", 25),
    ("I can't make it to {PLACES} on {DAYS}.", 30),
    ("It's been a long week, honestly.", 1),
    ("Let me know what time works for you on {DAYS}.", 20),
]
CLEANS = fill(TEMPL, PEOPLE=PEOPLE, PLACES=PLACES, DAYS=DAYS, THINGS=THINGS,
              VERBS=VERBS, COMPANIES=COMPANIES, FEELINGS=FEELINGS)

# casual / clumsy registers (verbatim must PRESERVE clumsiness — keep words)
CASUAL = [
    "I mean it could work but we'd have to test it first.",
    "So yeah, let's keep the scope tight for this one.",
    "Honestly the demo went way better than I expected.",
    "We should probably double check those numbers before we send it.",
    "I'm gonna grab a coffee, you want anything?",
    "It's kind of a mess right now but we'll sort it out.",
    "Just wanted to check in and see how it's going.",
    "We're a bit behind but I think we'll still make the deadline.",
    "That's exactly what I was thinking, let's do it.",
    "I don't think that's a good idea, but it's your call.",
    "She said she'd handle it, so we're good.",
    "Can we push it a week? I'm slammed right now.",
    "The thing is, nobody told me about the change.",
    "I'll circle back once I've talked to the team.",
    "We were running late so we just grabbed a cab.",
    "It's raining, so we'll probably drive instead.",
    "Let's grab lunch around noon and head over after.",
    "I haven't heard back from the vendor yet.",
    "They're saying it's too late to change the order.",
    "Who's leading the onboarding session tomorrow?",
]

# code / numbers / names weak-spot clean seeds (also corrupted -> verbatim)
WEAK_CLEAN = [
    "The bug is in the useEffect hook.", "Call the getUserData function after login.",
    "The API returns JSON over HTTPS.", "Push it to GitHub and open a pull request.",
    "We wrote the backend in TypeScript and the front end in React.",
    "Deploy it to AWS using the CLI.", "Set the MAX_RETRIES constant to three.",
    "The error code is 404.", "We shipped version 2.1 to production.",
    "The server is on port 8000.", "It happened back in 2024.",
    "Meet me in room 205 at 3:30.", "The invoice total is $420.",
    "The model has 7 billion parameters.", "Read pages 40 to 45 tonight.",
    "It's about 1,500 miles from here.", "The flight leaves at 7:45.",
    "I ordered the new iPhone from Amazon.", "Open the README.md and check config.py.",
    "Hit the /api/users endpoint with a GET request.", "We use Kubernetes and Docker.",
    "The CI/CD pipeline runs on GitHub Actions.", "It threw a NullPointerException.",
    "We migrated to Postgres from MySQL.", "The discount is 20 percent off.",
]
CLEANS += CASUAL + WEAK_CLEAN

# email/url: teach the model to LEAVE spellouts ALONE (the deterministic scaffold
# converts them). Fixes the 0.8B regression where it half-converted "at"->"@".
# The clean target keeps "at ... dot com" spelled out verbatim.
EMAIL_LEAVE = [
    "Email me at john at gmail dot com.", "Reach support at acme dot org.",
    "Send it to sarah dot lee at company dot io.", "The site is example dot com.",
    "Go to docs dot python dot org.", "Contact hello at my site dot net.",
    "Her address is priya dot patel at work dot com.", "Visit shop dot example dot co.",
    "Forward it to billing at vendor dot org.", "The link is github dot com slash repo.",
    "My handle is at john underscore doe.", "Ping me at marcus at startup dot ai.",
]
# NOTE (v4): EMAIL_LEAVE is now 0.8B-ONLY — added in the v4 assembly below, NOT
# folded into CLEANS (which feeds all tiers). The 2B/4B instead learn to CONVERT
# emails. Teaching one tier both "leave literal" and "convert" gives contradictory
# signals, which is what muddied v3.
# CLEANS += EMAIL_LEAVE   # (moved to 0.8B-only v4 pool)

# ----------------------------------------------------------- TIDY (authored)
# (verbose/redundant raw -> tidied target). Tidy = light grammar + de-clutter.
TIDY = [
    ("um so i was just kind of wondering if you maybe had a chance to look at the thing i sent you",
     "Did you get a chance to look at what I sent?"),
    ("the thing is is that like the report it just isnt really done yet you know",
     "The report isn't done yet."),
    ("so basically what im trying to say is that we should probably maybe think about pushing the deadline",
     "We should think about pushing the deadline."),
    ("i went to the store and i bought some milk and i also bought some bread and some eggs and stuff",
     "I went to the store and bought milk, bread, and eggs."),
    ("yeah so um the meeting that we had it kind of went on for way too long honestly",
     "The meeting went on for too long."),
    ("i just wanted to reach out and say that i really do appreciate all of the help that you gave me",
     "I really appreciate all your help."),
    ("so the client they came back and they said that they want like a few more days to review everything",
     "The client wants a few more days to review."),
    ("um i think that what we need to do is we need to kind of revisit the whole budget thing again",
     "We need to revisit the budget."),
    ("its just that theres so much stuff to do before the launch and not really enough time to do it",
     "There's a lot to do before the launch and not enough time."),
    ("basically the vendor they missed the deadline again and now everything is kind of pushed back",
     "The vendor missed the deadline again, so everything is pushed back."),
    ("so yeah i mean honestly the design it looks pretty good but the colors they feel a little bit off",
     "The design looks good, but the colors feel a little off."),
    ("um can you maybe just kind of double check those numbers one more time before we send it out",
     "Can you double check those numbers before we send it?"),
    ("i was thinking that maybe possibly we could meet up at some point next week if that works for you",
     "Could we meet up sometime next week?"),
    ("so the deploy it failed again this morning and im really not totally sure why it keeps doing that",
     "The deploy failed again this morning and I'm not sure why."),
    ("yeah we should probably just go ahead and book the tickets now before the prices they go up more",
     "We should book the tickets now before prices go up."),
    ("honestly theres a lot of moving parts here and i just want to make sure that nothing falls through",
     "There are a lot of moving parts; I want to make sure nothing falls through."),
    ("um so the new hire they start on monday and we still havent set up their laptop or their accounts",
     "The new hire starts Monday and we haven't set up their laptop or accounts."),
    ("i mean the feedback was mostly positive but a few people they mentioned that it felt kind of rushed",
     "The feedback was mostly positive, though a few people felt it was rushed."),
]

# ------------------------------------------------ FORMATTED (authored)
# (enumeration / multi-topic raw -> structured target with breaks/lists).
FORMATTED = [
    ("okay so for the launch we need to do three things first finalize the pricing second update the landing page and third brief the support team",
     "For the launch we need to do three things:\n\n1. Finalize the pricing\n2. Update the landing page\n3. Brief the support team"),
    ("um the agenda for today is first we review last weeks metrics then we talk about the roadmap and finally we do open q and a",
     "Agenda for today:\n\n1. Review last week's metrics\n2. Discuss the roadmap\n3. Open Q&A"),
    ("so for the trip we need to pack the tent the sleeping bags the water filter and dont forget the first aid kit",
     "For the trip, pack:\n\n- Tent\n- Sleeping bags\n- Water filter\n- First aid kit"),
    ("dear team thanks for all your hard work this quarter new paragraph we hit every target and i could not be prouder new paragraph lets keep the momentum going",
     "Dear team,\n\nThanks for all your hard work this quarter. We hit every target and I couldn't be prouder.\n\nLet's keep the momentum going."),
    ("the three priorities for the sprint are fixing the login bug improving the load time and adding the export feature",
     "The three priorities for the sprint are:\n\n1. Fix the login bug\n2. Improve the load time\n3. Add the export feature"),
    ("shopping list we need milk eggs bread coffee and some fruit for the week",
     "Shopping list:\n\n- Milk\n- Eggs\n- Bread\n- Coffee\n- Fruit for the week"),
    ("um so the steps to deploy are first run the tests then build the image then push to the registry and finally roll it out",
     "Steps to deploy:\n\n1. Run the tests\n2. Build the image\n3. Push to the registry\n4. Roll it out"),
    ("hi sarah just following up on our chat new paragraph could you send over the updated contract by friday new paragraph thanks so much",
     "Hi Sarah,\n\nJust following up on our chat. Could you send over the updated contract by Friday?\n\nThanks so much."),
]

# ------------------------------------------ TIDY at scale (verbosify)
# Insert REDUNDANT filler-words into a concise sentence -> verbose raw; the tidy
# target is the concise sentence (tidy = strip the redundancy, unlike verbatim
# which keeps every word). This is the actual verbatim-vs-tidy distinction.
_PAD = ["just", "really", "kind of", "sort of", "basically", "you know",
        "honestly", "actually", "i think", "i guess", "pretty much", "or whatever",
        "at this point", "to be honest", "i mean"]
def verbosify(concise: str) -> str:
    core = concise.rstrip(".!?").lower().replace("’", "'").replace("'", "")
    core = re.sub(r"[.,!?;:\"()]", " ", core)
    words = re.sub(r"\s+", " ", core).strip().split()
    out: list[str] = []
    if RNG.random() < 0.6:
        out.append(RNG.choice(["um", "uh", "so um", "yeah so", "okay so"]))
    for w in words:
        out.append(w)
        if RNG.random() < 0.15:
            out.append(RNG.choice(_PAD))
    return " ".join(out)

# concise, well-formed seeds make good tidy targets (reuse the clean pools)
TIDY_SEEDS = [c for c in CLEANS if len(c.split()) <= 14] + CASUAL
tidy_synth = []
for c in TIDY_SEEDS:
    for _ in range(2):
        tidy_synth.append((verbosify(c), c))

# ------------------------------------------ FORMATTED at scale (templates)
def numbered(items): return ":\n\n" + "\n".join(f"{i+1}. {x}" for i, x in enumerate(items))
def bulleted(items): return ":\n\n" + "\n".join(f"- {x}" for x in items)
ACTIONS = ["finalize the pricing", "update the landing page", "brief the support team",
           "run the tests", "fix the login bug", "improve the load time", "add the export feature",
           "review the metrics", "confirm the venue", "send the invites", "order the catering",
           "book the flights", "draft the agenda", "set up the accounts", "back up the database",
           "rotate the keys", "renew the certificate", "update the docs", "ping the client",
           "merge the branch", "tag the release", "notify the team"]
ITEMS = ["milk", "eggs", "bread", "coffee", "the tent", "the sleeping bags", "the water filter",
         "the first aid kit", "sunscreen", "the charger", "the passports", "snacks", "a map",
         "the laptop", "the badge", "the headphones", "the adapter"]
fmt_synth = []
for _ in range(180):
    n = RNG.choice([3, 3, 4, 4, 5])
    picks = RNG.sample(ACTIONS, n)
    spoken = "first " + " then ".join(picks) if RNG.random() < 0.5 else \
             "we need to " + " ".join(picks[:-1]) + " and " + picks[-1]
    spoken = RNG.choice(["um ", "so ", "okay so ", ""]) + spoken
    body = "Here's the plan" + numbered([p[0].upper() + p[1:] for p in picks])
    fmt_synth.append((spoken, body))
for _ in range(120):
    n = RNG.choice([4, 5, 5, 6])
    picks = RNG.sample(ITEMS, n)
    spoken = RNG.choice(["shopping list we need ", "we need to grab ", "dont forget "]) + \
             " ".join(picks[:-1]) + " and " + picks[-1]
    body = "Shopping list" + bulleted([p[0].upper() + p[1:] for p in picks])
    fmt_synth.append((spoken, body))

# ---- v4 FORMATTED: enterprise scenarios (4B-only) — the formatted pool was
# consumer-skewed (123 shopping lists, 0 action items). These add the structures
# enterprise actually dictates: action items, status updates, structured emails,
# mixed docs, plus restraint cases (prose that must STAY prose). ----
def _cap(s): return (s[0].upper() + s[1:]) if s else s
enterprise_fmt = []

# (a) action items / meeting minutes (owner + due date) -> bulleted owners
AI_PEOPLE = ["Sarah", "John", "Mike", "Priya", "David", "Amanda", "Raj", "Carlos",
             "Elena", "Marcus", "Nina", "Grace", "Tom", "Fatima", "Leo", "Omar"]
AI_TASK = ["finish the report", "review the budget", "send the contract", "update the deck",
           "schedule the demo", "follow up with the client", "fix the login bug",
           "prepare the slides", "book the venue", "draft the proposal", "test the integration",
           "onboard the new hire", "renew the licenses", "audit the accounts", "ship the hotfix",
           "set up the staging environment", "write the release notes", "confirm the headcount"]
AI_DUE = ["by Friday", "by Monday", "by Wednesday", "by Thursday", "by end of day",
          "by next week", "by tomorrow", "this week", "by the 15th", "", ""]
AI_VERB = ["will", "is going to", "needs to", "should", "is gonna", "has to"]
AI_LEAD = ["so from the meeting", "okay action items from the standup", "to recap who's doing what",
           "heres what we agreed on", "um so the takeaways are", "for next steps",
           "quick recap of owners", "so to summarize the action items"]
for _ in range(80):
    n = RNG.choice([2, 3, 3, 4])
    ppl = RNG.sample(AI_PEOPLE, n); tsk = RNG.sample(AI_TASK, n)
    due = [RNG.choice(AI_DUE) for _ in range(n)]
    sp, ln = [], []
    for p, t, d in zip(ppl, tsk, due):
        v = RNG.choice(AI_VERB)
        sp.append(f"{p.lower()} {v} {t}" + (f" {d.lower()}" if d else ""))
        ln.append(f"- {p}: {_cap(t)}" + (f" {d}" if d else ""))
    spoken = RNG.choice(AI_LEAD) + " " + RNG.choice([" and ".join(sp), " then ".join(sp), " ".join(sp)])
    enterprise_fmt.append((spoken, "Action items:\n\n" + "\n".join(ln)))

# (b) status / standup updates -> did / doing / blocked
SU_DONE = ["finished the login flow", "wrapped up the API docs", "deployed the hotfix",
           "closed three tickets", "reviewed the open PRs", "set up the staging env",
           "migrated the database", "wrote the unit tests", "shipped the dashboard",
           "fixed the billing bug", "completed the security review"]
SU_DOING = ["working on the payment integration", "building the analytics dashboard",
            "refactoring the auth module", "writing the migration script",
            "testing the new endpoint", "fixing the flaky tests", "updating the docs",
            "reviewing the vendor contracts", "scoping the next milestone"]
SU_BLOCKED = ["waiting on the API keys from the vendor", "blocked on the design review",
              "need access to the prod logs", "waiting for QA signoff",
              "blocked on the contract approval", "waiting on legal to clear it"]
for _ in range(50):
    d, t = RNG.choice(SU_DONE), RNG.choice(SU_DOING)
    blocked = RNG.random() < 0.7
    spoken = (RNG.choice(["for my update", "heres my standup", "quick status", "um so my update is", "status update"])
              + f" yesterday i {d} today im {t}" + (f" and im blocked on {RNG.choice(SU_BLOCKED)}" if blocked else ""))
    b = RNG.choice(SU_BLOCKED)
    clean = "Update:\n\n" + f"- Yesterday: {_cap(d)}\n- Today: {_cap(t)}" + (f"\n- Blocked: {_cap(b)}" if blocked else "")
    # rebuild spoken's blocked clause to match the chosen b
    if blocked:
        spoken = (RNG.choice(["for my update", "heres my standup", "quick status", "status update"])
                  + f" yesterday i {d} today im {t} and im blocked on {b}")
    enterprise_fmt.append((spoken, clean))

# (c) structured emails with PARAGRAPH inference (the 21-example soft spot)
EM_GREET = [("hi team", "Hi team,"), ("hi sarah", "Hi Sarah,"), ("hello everyone", "Hello everyone,"),
            ("hi all", "Hi all,"), ("hey folks", "Hey folks,"), ("hi jordan", "Hi Jordan,")]
EM_B1 = ["i wanted to give you a quick update on the project",
         "following up on our conversation from yesterday",
         "i'm writing to confirm the details for next week",
         "thanks for your patience while we sorted this out",
         "i wanted to flag a couple of things before the deadline"]
EM_B2 = ["we hit all our milestones this sprint and the client is happy",
         "the numbers came in stronger than we expected",
         "the timeline is tight but we're on track",
         "there are a few open items we still need to close",
         "everything is on schedule for the launch"]
EM_ASK = ["please review the contract before friday", "let me know if you have any questions",
          "could you send over the latest figures", "can we set up a call early next week",
          "please confirm your availability"]
EM_CLOSE = [("thanks alex", "Thanks,\nAlex"), ("best regards jordan", "Best regards,\nJordan"),
            ("cheers sam", "Cheers,\nSam"), ("thanks so much priya", "Thanks so much,\nPriya"),
            ("best david", "Best,\nDavid")]
def _capask(a):
    return _cap(a.replace("friday", "Friday"))
for _ in range(45):
    gs, gw = RNG.choice(EM_GREET); b1 = RNG.choice(EM_B1); b2 = RNG.choice(EM_B2)
    ask = RNG.choice(EM_ASK); cs, cw = RNG.choice(EM_CLOSE)
    spoken = f"{gs} {b1} {b2} that said {ask} {cs}"
    clean = f"{gw}\n\n{_cap(b1)}. {_cap(b2)}.\n\nThat said, {ask.replace('friday','Friday')}.\n\n{cw}"
    enterprise_fmt.append((spoken, clean))

# (d) mixed structure: heading + headline + numbered priorities
MIX_TOPIC = [("quarterly review", "Quarterly review"), ("project update", "Project update"),
             ("sprint summary", "Sprint summary"), ("weekly report", "Weekly report"),
             ("board update", "Board update")]
MIX_HEAD = ["revenue is up twelve percent", "we shipped the new feature on time",
            "churn dropped to two percent", "we closed five new deals",
            "the migration is complete", "we hit ninety eight percent uptime"]
MIX_PRIO = ["hiring", "marketing", "product", "onboarding", "retention", "infrastructure",
            "sales", "support", "compliance", "fundraising"]
for _ in range(30):
    ts, tw = RNG.choice(MIX_TOPIC); h = RNG.choice(MIX_HEAD); n = RNG.choice([3, 3, 4])
    pr = RNG.sample(MIX_PRIO, n)
    spoken = f"{ts} {h} the priorities for next quarter are {' '.join(pr[:-1])} and {pr[-1]}"
    clean = f"{tw}\n\n{_cap(h)}.\n\nPriorities for next quarter:\n\n" + "\n".join(f"{i+1}. {_cap(p)}" for i, p in enumerate(pr))
    enterprise_fmt.append((spoken, clean))

# (e) RESTRAINT: enterprise prose that is a single thought -> stays prose (protects
# the no-over-format behavior as we add structured examples)
RESTRAINT_FMT = [
    ("just wanted to flag that the vendor pushed back the delivery date so we might slip a few days",
     "Just wanted to flag that the vendor pushed back the delivery date, so we might slip a few days."),
    ("the client called and theyre happy with the latest build so no changes needed",
     "The client called and they're happy with the latest build, so no changes needed."),
    ("we should probably loop in legal before we sign anything on this one",
     "We should probably loop in legal before we sign anything on this one."),
    ("the deploy went fine but were keeping an eye on the error rate for now",
     "The deploy went fine, but we're keeping an eye on the error rate for now."),
    ("i think the new pricing makes sense but lets run it by finance first",
     "I think the new pricing makes sense, but let's run it by finance first."),
    ("heads up the standup is moving to ten thirty starting next week",
     "Heads up, the standup is moving to 10:30 starting next week."),
    ("the candidate accepted the offer and starts on the first of the month",
     "The candidate accepted the offer and starts on the first of the month."),
    ("we came in under budget this quarter which gives us some room to hire",
     "We came in under budget this quarter, which gives us some room to hire."),
    ("the outage is resolved and were writing up the postmortem now",
     "The outage is resolved and we're writing up the postmortem now."),
    ("just confirming the all hands is still on for thursday afternoon",
     "Just confirming the all-hands is still on for Thursday afternoon."),
    ("the contract is with their legal team so we should hear back this week",
     "The contract is with their legal team, so we should hear back this week."),
    ("i pushed the fix and the failing tests are green again",
     "I pushed the fix and the failing tests are green again."),
    ("we lost the deal but they said to circle back next quarter",
     "We lost the deal, but they said to circle back next quarter."),
    ("the demo went really well and they asked for a follow up call",
     "The demo went really well and they asked for a follow-up call."),
    ("nothing blocking on my end im just waiting on the design review",
     "Nothing blocking on my end, I'm just waiting on the design review."),
    ("the migration finished overnight and everything looks healthy",
     "The migration finished overnight and everything looks healthy."),
    ("we need another engineer on this if we want to hit the deadline",
     "We need another engineer on this if we want to hit the deadline."),
    ("the board was happy with the numbers and approved the new budget",
     "The board was happy with the numbers and approved the new budget."),
    ("im out friday but ill have my laptop if anything urgent comes up",
     "I'm out Friday, but I'll have my laptop if anything urgent comes up."),
    ("the vendor finally sent the invoice so accounting can process it",
     "The vendor finally sent the invoice, so accounting can process it."),
    ("we hit our signup target two weeks early which is a great sign",
     "We hit our signup target two weeks early, which is a great sign."),
    ("lets hold off on announcing until the contract is fully signed",
     "Let's hold off on announcing until the contract is fully signed."),
    ("the support queue is back to normal after the weekend spike",
     "The support queue is back to normal after the weekend spike."),
    ("i reviewed the proposal and it looks solid just a couple of typos",
     "I reviewed the proposal and it looks solid, just a couple of typos."),
    ("were going to need sign off from security before this ships",
     "We're going to need sign-off from security before this ships."),
    ("the new hire is ramping up fast and already shipped their first pr",
     "The new hire is ramping up fast and already shipped their first PR."),
    ("traffic is up forty percent since the launch and infra is holding",
     "Traffic is up 40% since the launch and infra is holding."),
    ("the client wants a discount but i think we should hold the line",
     "The client wants a discount, but I think we should hold the line."),
    ("everything on the roadmap is still on track for the q3 release",
     "Everything on the roadmap is still on track for the Q3 release."),
    ("i synced with marketing and the campaign goes live on monday",
     "I synced with marketing and the campaign goes live on Monday."),
]
enterprise_fmt += RESTRAINT_FMT

# ============================== v4 ADDITIONS ==============================
# Targeted gaps from the 1,000-case eval. Tier-blocking is enforced in the
# assembly below:
#   foreign / anti-ellipsis / repetition / reinforce -> ALL tiers (verbatim)
#   email-LEAVE + line-break-literal                 -> 0.8B ONLY (scaffold owns symbols)
#   email/url CONVERSION                             -> 2B + 4B ONLY (style-bleed guard)
#   hard email                                       -> 4B ONLY

# ---- Pool A: foreign passthrough (clean BUT keep language, never translate) ----
def corrupt_lang(clean, fillers):
    t = re.sub(r'[.,!?;:"()¿¡]', " ", clean.lower())
    out = []
    if RNG.random() < 0.6:
        out.append(RNG.choice(fillers))
    for w in re.sub(r"\s+", " ", t).strip().split():
        if RNG.random() < 0.08:
            out.append(RNG.choice(fillers))
        out.append(w)
    return " ".join(out)

FOREIGN = [
    (["euh", "ben", "alors", "du coup", "hein"], [
        "Bonjour, je voulais vous parler du projet.",
        "Nous devrions reporter la réunion à demain.",
        "Le client a approuvé la nouvelle maquette.",
        "J'ai envoyé le contrat ce matin.",
        "Pouvez-vous confirmer votre présence avant vendredi ?",
        "La livraison est prévue pour lundi prochain.",
        "Je pense que nous avons besoin de plus de temps.",
        "Merci beaucoup pour votre aide avec le rapport.",
        "Où est la station de métro la plus proche ?",
        "Le budget doit être validé cette semaine.",
        "Nous avons terminé le premier brouillon hier soir.",
        "L'équipe est prête pour le lancement."]),
    (["eh", "este", "o sea", "pues", "bueno"], [
        "Hola, quería preguntarte sobre la reunión.",
        "Necesito el informe para la presentación del viernes.",
        "El equipo está listo para el lanzamiento.",
        "La factura debe pagarse antes de fin de mes.",
        "¿Cuándo llega el próximo tren a la ciudad?",
        "Por favor envíame el documento antes del mediodía.",
        "El vuelo sale a las ocho de la mañana.",
        "Necesitamos aprobar el presupuesto esta semana.",
        "La reunión se canceló por el mal tiempo.",
        "Gracias por tu ayuda con el proyecto.",
        "El cliente quiere unos días más para revisar.",
        "Vamos a reservar los vuelos esta noche."]),
    (["ähm", "äh", "also", "halt", "ja"], [
        "Guten Tag, ich wollte über das Budget sprechen.",
        "Können wir das Meeting auf morgen verschieben?",
        "Die Präsentation ist für Donnerstag geplant.",
        "Ich habe die Datei an das Team geschickt.",
        "Das Produkt wird nächsten Monat veröffentlicht.",
        "Wir treffen uns um drei Uhr im Büro.",
        "Bitte bestätigen Sie Ihre Teilnahme bis Freitag.",
        "Der Bericht muss bis Ende der Woche fertig sein.",
        "Ich freue mich auf unsere Zusammenarbeit.",
        "Wir brauchen mehr Zeit für die Tests.",
        "Der Kunde hat den Entwurf genehmigt.",
        "Das Flugzeug landet um acht Uhr abends."]),
    (["ehm", "allora", "cioè", "insomma", "ecco"], [
        "Buongiorno, volevo parlarti del nuovo progetto.",
        "Abbiamo bisogno di più tempo per i test.",
        "Il progetto è in ritardo di una settimana.",
        "Vorrei prenotare un tavolo per quattro persone.",
        "La consegna è prevista per lunedì prossimo.",
        "Ho inviato il contratto questa mattina.",
        "Il cliente ha approvato il nuovo design.",
        "Dobbiamo approvare il budget questa settimana.",
        "Ci vediamo alle tre in ufficio.",
        "Grazie mille per il tuo aiuto con il rapporto."]),
    (["hum", "né", "tipo", "então", "olha"], [
        "Bom dia, eu queria falar sobre o projeto.",
        "Precisamos de mais tempo para os testes.",
        "O cliente aprovou o novo design.",
        "Vou enviar o contrato esta tarde.",
        "A reunião foi remarcada para sexta-feira.",
        "O voo sai às oito da manhã.",
        "Obrigado pela sua ajuda com o relatório.",
        "Precisamos aprovar o orçamento esta semana.",
        "A entrega está prevista para segunda-feira.",
        "A equipe está pronta para o lançamento."]),
]
foreign_pairs = []
for fillers, sents in FOREIGN:
    for s in sents:
        seen = set()
        for _ in range(3):
            r = corrupt_lang(s, fillers)
            if r and r not in seen:
                seen.add(r); foreign_pairs.append((r, s))

# ---- Pool G: anti-ellipsis (pauses / trailing-off -> clean, NEVER "...") ----
# Directly targets the live bug: the model inserted "..." on a spoken pause.
ANTI_ELLIPSIS = [
    ("so i was thinking um you know maybe we could just wait and see",
     "So I was thinking maybe we could just wait and see."),
    ("and then i was like uh", "And then I was like."),
    ("i dont know its just kind of complicated", "I don't know, it's just kind of complicated."),
    ("we need to um think about this a bit more", "We need to think about this a bit more."),
    ("wait for it here it comes", "Wait for it, here it comes."),
    ("hold on let me uh let me check", "Hold on, let me check."),
    ("yeah so anyway where was i", "Yeah, so anyway, where was I?"),
    ("its just that well you know how it is", "It's just that, well, you know how it is."),
    ("hmm let me think about that for a sec", "Let me think about that for a sec."),
    ("so the thing is um its complicated", "So the thing is, it's complicated."),
    ("i guess what im trying to say is we should wait", "I guess what I'm trying to say is we should wait."),
    ("it was fine i mean it was okay i guess", "It was fine, I mean it was okay I guess."),
    ("we could maybe possibly push it to next week", "We could maybe push it to next week."),
    ("anyway um yeah thats basically it", "Anyway, yeah, that's basically it."),
    ("so like i was gonna say something but i forgot", "So I was gonna say something but I forgot."),
    ("the report its uh its almost done", "The report is almost done."),
    ("i think we should just you know go for it", "I think we should just go for it."),
    ("let me get back to you on that one", "Let me get back to you on that one."),
    ("its kind of a long story but basically it worked", "It's kind of a long story, but basically it worked."),
    ("um so where do i even start with this", "So where do I even start with this?"),
    ("honestly i havent really decided yet", "Honestly, I haven't really decided yet."),
    ("we were gonna go but then it rained so", "We were gonna go but then it rained."),
    ("i mean if you want we could try again later", "I mean, if you want, we could try again later."),
    ("so yeah thats the plan for now i think", "So yeah, that's the plan for now I think."),
    ("give me a sec im still loading the page", "Give me a sec, I'm still loading the page."),
    ("uh let me see what else was there", "Let me see what else was there."),
    ("its more of a nice to have than a must have", "It's more of a nice-to-have than a must-have."),
    ("we should probably just call it a day", "We should probably just call it a day."),
    ("i was about to say something but never mind", "I was about to say something, but never mind."),
    ("so basically it is what it is at this point", "So basically, it is what it is at this point."),
    # Whisper emits "..." for a spoken PAUSE; the model must strip it, not keep it
    # (the reported live bug). Input has the ellipsis; target replaces it with the
    # right punctuation.
    ("so the plan is ... we ship on friday", "So the plan is, we ship on Friday."),
    ("hold on ... let me find it", "Hold on, let me find it."),
    ("i was thinking ... we should wait", "I was thinking we should wait."),
    ("and then ... it just stopped working", "And then it just stopped working."),
    ("wait for it ... here it comes", "Wait for it, here it comes."),
    ("the thing is ... we ran out of time", "The thing is, we ran out of time."),
    ("i mean ... its complicated", "I mean, it's complicated."),
    ("so yeah ... thats where we landed", "So yeah, that's where we landed."),
    ("let me check ... okay found it", "Let me check. Okay, found it."),
    ("we could ... or we could just wait", "We could, or we could just wait."),
    ("honestly ... i have no idea", "Honestly, I have no idea."),
    ("give me a sec ... almost there", "Give me a sec, almost there."),
    ("its just ... never mind", "It's just, never mind."),
    ("dont be too afraid to add ... too much", "Don't be too afraid to add too much."),
    ("and ... thats basically it", "And that's basically it."),
]

# ---- Pool H: mid-phrase repetition (collapse repeats, incl. filler-separated) ----
REPETITION = [
    ("we should we should just do it", "We should just do it."),
    ("i think i think we need more time", "I think we need more time."),
    ("the the the meeting got moved", "The meeting got moved."),
    ("dont be afraid to add too too much", "Don't be afraid to add too much."),
    ("dont be afraid to add too uh too much", "Don't be afraid to add too much."),
    ("go to to the store", "Go to the store."),
    ("it was um it was really good", "It was really good."),
    ("can you can you send it over", "Can you send it over?"),
    ("we need to we need to leave soon", "We need to leave soon."),
    ("she she already left", "She already left."),
    ("its its not working again", "It's not working again."),
    ("let me let me check the calendar", "Let me check the calendar."),
    ("they they dont know yet", "They don't know yet."),
    ("i was i was about to call you", "I was about to call you."),
    ("just just give me a second", "Just give me a second."),
    ("and and then it crashed", "And then it crashed."),
    ("we have have a problem", "We have a problem."),
    ("you you have to see this", "You have to see this."),
    ("we we should go now", "We should go now."),
    ("add too too many of them", "Add too many of them."),
    ("its really um really important", "It's really important."),
    ("i need to to finish this first", "I need to finish this first."),
    ("can we can we move the call up", "Can we move the call up?"),
    ("he he said it was fine", "He said it was fine."),
    ("so so what happened was", "So what happened was."),
    ("that that doesnt make sense", "That doesn't make sense."),
    ("im im not sure about that", "I'm not sure about that."),
    ("do do you have a minute", "Do you have a minute?"),
    ("now now is a good time", "Now is a good time."),
    ("please please send it today", "Please send it today."),
]
for w, W in [("the", "The"), ("we", "We"), ("they", "They"), ("you", "You"),
             ("it", "It"), ("just", "Just"), ("can", "Can")]:
    REPETITION.append((f"{w} {w} need to talk about this", f"{W} need to talk about this."))

# ---- Pool F: verbatim reinforcement (corrupt -> verbatim; hold fidelity) ----
REINFORCE_CLEAN = [
    "I can't believe they shipped it without testing.",
    "This is fucking ridiculous, the build broke again.",
    "We won't make the deadline at this rate.",
    "Don't forget to lock the door when you leave.",
    "She doesn't think it's ready yet.",
    "They're not going to like this change.",
    "I'm heading out, I'll call you later.",
    "That's not what I meant, let me explain.",
    "It's been one hell of a week, honestly.",
    "We've gone over this a dozen times already.",
    "He couldn't find the file anywhere.",
    "You're going to want to see this.",
    "I haven't heard back from them yet.",
    "We shouldn't rush the decision.",
    "It isn't finished, but it's close.",
    "They've agreed to the new terms.",
    "Where's the report you promised me?",
    "I'd rather wait until Monday.",
    "We're slammed, so don't expect a quick reply.",
    "Honestly, that meeting was a complete waste of time.",
    "Let's keep this between us for now.",
    "She's the one who approved the budget.",
    "I'm not comfortable signing off on that yet.",
    "We can't afford another delay this quarter.",
    "You've done a great job on this, seriously.",
    "It's your call, but I wouldn't risk it.",
    "They were supposed to be here an hour ago.",
    "I think we're overcomplicating this.",
    "We'll figure it out, we always do.",
    "Damn, I forgot to send the invoice again.",
]
reinforce_pairs = [(r, c) for r, c, _ in verbatim_pairs(REINFORCE_CLEAN, per=2)]

# ---- Profanity PRESERVATION reinforcement (v4.1) ----
# The v4 2B started DELETING mid-phrase profanity (a side-effect of the
# self-correction COLLAPSE training making it deletion-happy). These teach
# "profanity is NEVER removed, even mid-phrase or in odd grammar." All tiers.
PROFANITY_CLEAN = [
    "This fucking printer keeps jamming on me.",
    "I'm so damn tired of these endless meetings.",
    "That was a complete shit show from start to finish.",
    "We're so fucking behind on this release.",
    "What the hell happened to the staging server?",
    "The whole damn thing crashed right before the demo.",
    "That client is being a real asshole about the invoice.",
    "The fucking wifi dropped again in the middle of the call.",
    "I'm so pissed about the deadline getting moved.",
    "This is such bullshit, they changed the specs again.",
    "The goddamn build has been red for three hours.",
    "Honestly the new policy is total crap.",
    "That meeting was a complete waste of my damn time.",
    "I'm fucking exhausted after this sprint.",
    "The shit hit the fan when the database went down.",
    "Who the hell approved this without telling me?",
    "This stupid app crashes every single time I open it.",
    "We're in deep shit if we miss this deadline.",
    "The damn vendor missed the deadline a third time.",
    "Stop being such a dick about the code review.",
    "He's a complete asshole to the support team.",
    "What a shit way to end the quarter.",
    "I cannot believe this fucking bug came back again.",
    "The bitch of it is we already paid the invoice.",
    "That goddamn meeting ran way over again.",
    "I'm so fucking frustrated with this rollout.",
    "The login is broken as hell on mobile.",
    "We lost the deal and it's a real kick in the ass.",
    "This whole codebase is a fucking mess.",
    "The client ghosted us, which is bullshit.",
    # odd-placement intensifiers (the exact pattern the 2B was deleting)
    "We are so bastard behind schedule it's not even funny.",
    "The shit printer jammed again right before the deadline.",
    "I'm so fuck done with this whole project.",
    "This fucking situation is completely out of control.",
    "That damn deploy broke production again.",
    "The stupid migration corrupted half the rows.",
    "He's being a goddamn nightmare about the timeline.",
    "It's a shit deal but we don't have a choice.",
    "The whole fucking quarter has been a disaster.",
    "I'm so damn done explaining this to them.",
    "Stop sending me this bullshit paperwork.",
    "The hell of it is nobody warned us.",
    "That asshole vendor raised the price again.",
    "We are so screwed if the demo crashes.",
    "This goddamn laptop won't connect to the projector.",
]
profanity_pairs = [(r, c) for r, c, _ in verbatim_pairs(PROFANITY_CLEAN, per=2)]

# ---- Pool B: line-break LEAVE-LITERAL (0.8B only; scaffold turns it into \n) ----
LINEBREAK_CLEAN = [
    "Dear team new line we have an update.",
    "First point is done new paragraph now the second point.",
    "Hi Sarah new line hope you're well new line quick question.",
    "Section one new paragraph section two.",
    "Intro new line body new line closing.",
    "Morning tasks new paragraph afternoon tasks.",
    "Thanks again new paragraph best regards Alex.",
    "Title new line subtitle new line body text.",
    "Step one prep the data new line step two train the model.",
    "Problem new paragraph solution.",
    "Name new line title new line company.",
    "Greeting new line message new line signature.",
    "Summary new paragraph next steps.",
    "Question one new paragraph question two.",
    "Header new paragraph footer.",
    "Before new line after.",
    "Opening line new line second line.",
    "Draft one new paragraph draft two.",
    "Hi team new line the launch is on track new line let me know if you have questions.",
    "Topic one new paragraph topic two new paragraph topic three.",
]
linebreak_pairs = [(r, c) for r, c, _ in verbatim_pairs(LINEBREAK_CLEAN, per=2)]

# ---- EMAIL_LEAVE -> 0.8B only (corrupt the spell-out, target keeps it literal) ----
email_leave_pairs = [(r, c) for r, c, _ in verbatim_pairs(EMAIL_LEAVE, per=3)]

# ---- Pool C/D: email + url CONVERSION (2B + 4B only) ----
EMAIL_LOCAL = [
    ("jordan", "jordan"), ("alex", "alex"), ("sam", "sam"), ("taylor", "taylor"),
    ("morgan", "morgan"), ("casey", "casey"), ("support", "support"), ("hello", "hello"),
    ("billing", "billing"), ("info", "info"), ("admin", "admin"), ("sales", "sales"),
    ("contact", "contact"), ("sarah dot lee", "sarah.lee"), ("mike dot jones", "mike.jones"),
    ("priya dot patel", "priya.patel"), ("john dot smith", "john.smith"),
    ("dana dot cho", "dana.cho"), ("marcus underscore t", "marcus_t"), ("a dot kumar", "a.kumar"),
]
EMAIL_DOM = ["gmail", "outlook", "company", "acme", "startup", "work", "vendor", "mail",
             "proton", "yahoo", "business", "project", "service", "group", "cloud", "data",
             "shop", "team"]
EMAIL_TLD = ["com", "org", "io", "net", "co", "dev", "ai", "edu", "app", "biz"]
EMAIL_LEAD = [("email me at", "Email me at"), ("reach me at", "Reach me at"),
              ("send it to", "Send it to"), ("my address is", "My address is"),
              ("contact", "Contact"), ("forward it to", "Forward it to"),
              ("you can reach me at", "You can reach me at"), ("write to", "Write to"),
              ("ping", "Ping")]
email_conv = []
_seen = set()
while len(email_conv) < 170:
    ls, lw = RNG.choice(EMAIL_LOCAL); dom = RNG.choice(EMAIL_DOM); tld = RNG.choice(EMAIL_TLD)
    leadl, leadw = RNG.choice(EMAIL_LEAD)
    raw = f"{leadl} {ls} at {dom} dot {tld}"
    if raw in _seen:
        continue
    _seen.add(raw)
    clean = f"{leadw} {lw}@{dom}.{tld}."
    if RNG.random() < 0.3:
        raw = RNG.choice(["um ", "uh ", "so ", "okay "]) + raw
    email_conv.append((raw, clean))

URL_SUB = ["docs", "api", "blog", "shop", "app", "help", "status", "store", "news", "maps", "", "", ""]
URL_DOM = ["github", "python", "google", "stripe", "example", "service", "company", "product",
           "mozilla", "vercel", "wikipedia", "notion", "ycombinator"]
URL_TLD = ["com", "org", "io", "net", "co", "dev", "app"]
URL_LEAD = [("go to", "Go to"), ("the site is", "The site is"), ("visit", "Visit"),
            ("check", "Check"), ("the link is", "The link is"), ("its at", "It's at"),
            ("head to", "Head to")]
url_conv = []
_seen = set()
while len(url_conv) < 95:
    sub = RNG.choice(URL_SUB); dom = RNG.choice(URL_DOM); tld = RNG.choice(URL_TLD)
    leadl, leadw = RNG.choice(URL_LEAD)
    if sub:
        raw = f"{leadl} {sub} dot {dom} dot {tld}"; web = f"{sub}.{dom}.{tld}"
    else:
        raw = f"{leadl} {dom} dot {tld}"; web = f"{dom}.{tld}"
    path = ""
    if RNG.random() < 0.35:
        p, pw = RNG.choice([("repo", "/repo"), ("docs", "/docs"), ("users", "/users"),
                            ("team slash app", "/team/app"), ("login", "/login"), ("about", "/about")])
        raw += f" slash {p}"; path = pw
    if raw in _seen:
        continue
    _seen.add(raw)
    url_conv.append((raw, f"{leadw} {web}{path}."))

# ---- Pool E: hard email (4B only) — multi-word hosts, plus-addressing ----
HARD_EMAIL = [
    ("her email is priya dot patel at my company dot com", "Her email is priya.patel@mycompany.com."),
    ("send it to billing plus invoices at vendor dot net", "Send it to billing+invoices@vendor.net."),
    ("reach me at j dot s dot obrien at law firm dot com", "Reach me at j.s.obrien@lawfirm.com."),
    ("contact us at hello at my startup dot io", "Contact us at hello@mystartup.io."),
    ("the address is first dot last at big corp dot com", "The address is first.last@bigcorp.com."),
    ("email it to noreply at notifications dot app", "Email it to noreply@notifications.app."),
    ("forward to accounts payable at the firm dot com", "Forward to accountspayable@thefirm.com."),
    ("ping me at dev plus alerts at service dot io", "Ping me at dev+alerts@service.io."),
    ("write to careers at our company dot org", "Write to careers@ourcompany.org."),
    ("her work email is a dot b dot chen at research lab dot edu", "Her work email is a.b.chen@researchlab.edu."),
    ("send the invoice to ap at global vendors dot net", "Send the invoice to ap@globalvendors.net."),
    ("my personal one is jane dot doe ninety nine at gmail dot com", "My personal one is jane.doe99@gmail.com."),
    ("reach support plus urgent at help desk dot com", "Reach support+urgent@helpdesk.com."),
    ("the alias is team dash eng at start up dot ai", "The alias is team-eng@startup.ai."),
    ("contact me at r dot patel at my new company dot io", "Contact me at r.patel@mynewcompany.io."),
]

# ---- Self-correction COLLAPSE on explicit markers (2B/4B verbatim ONLY) ----
# "scratch that" / "no wait" / "I mean" are spoken EDIT commands; honoring them is
# a verbatim behavior. The 0.8B can't reliably pick the span to delete (a wrong
# deletion is worse than none), so it keeps them literal — capability-gated exactly
# like email conversion. Marker-LESS swaps are left alone (too ambiguous).
SELFCORR_AUTH = [
    ("send it on monday scratch that tuesday", "Send it on Tuesday."),
    ("the total is fifty dollars i mean fifteen dollars", "The total is fifteen dollars."),
    ("book a table for four no wait make it six", "Book a table for six."),
    ("turn left at the light actually turn right", "Turn right at the light."),
    ("meet at noon no make it one", "Meet at one."),
    ("call sarah i mean call mike", "Call Mike."),
    ("the deadline is the fifth scratch that the fifteenth", "The deadline is the fifteenth."),
    ("ship it to chicago no the denver office", "Ship it to the Denver office."),
    ("we need ten units scratch that twenty units", "We need twenty units."),
    ("set the timer for five minutes make that ten", "Set the timer for ten minutes."),
    ("ill have the salad no actually the soup", "I'll have the soup."),
    ("its on the second floor wait the third floor", "It's on the third floor."),
    ("the password is admin no its root", "The password is root."),
    ("lets meet tuesday or rather wednesday", "Let's meet Wednesday."),
    ("email it to sarah actually email it to me", "Email it to me."),
    ("the flight is at six no wait seven", "The flight is at seven."),
    ("bring three chairs i mean four", "Bring four chairs."),
    ("the meeting is in room 205 scratch that 210", "The meeting is in room 210."),
    ("send the report to john no make it the whole team", "Send the report to the whole team."),
    ("we leave at eight no actually nine", "We leave at nine."),
    ("color it blue no wait green", "Color it green."),
    ("the budget is fifty thousand i mean sixty thousand", "The budget is sixty thousand."),
    ("call me at three no four works better", "Call me at four."),
    ("park on the left scratch that the right side", "Park on the right side."),
    ("invite ten people make it fifteen", "Invite fifteen people."),
    ("the file is in documents no its in downloads", "The file is in downloads."),
    ("use the blue template actually the red one", "Use the red template."),
    ("we need it by friday or rather thursday", "We need it by Thursday."),
    ("the train leaves at noon scratch that twelve thirty", "The train leaves at twelve thirty."),
    ("reserve it under smith no wait under jones", "Reserve it under Jones."),
]
SC_GROUPS = [
    (("meet at", "Meet at"), [("noon", "one", "one"), ("three", "four", "four"),
                              ("five", "six", "six"), ("nine", "ten", "ten")]),
    (("send it to", "Send it to"), [("chicago", "denver", "Denver"), ("sarah", "mike", "Mike"),
                                    ("the london office", "the berlin office", "the Berlin office")]),
    (("set the timer for", "Set the timer for"), [("five minutes", "ten minutes", "ten minutes"),
                                                  ("two minutes", "three minutes", "three minutes")]),
    (("color it", "Color it"), [("blue", "green", "green"), ("red", "orange", "orange")]),
    (("park on the", "Park on the"), [("left", "right", "right")]),
    (("book a table for", "Book a table for"), [("four", "six", "six"), ("two", "three", "three")]),
    (("schedule it for", "Schedule it for"), [("monday", "tuesday", "Tuesday"),
                                              ("friday", "thursday", "Thursday")]),
    (("bring", "Bring"), [("three chairs", "four chairs", "four chairs")]),
    (("set it to", "Set it to"), [("twenty degrees", "twenty two degrees", "twenty-two degrees")]),
]
SC_MARK = ["scratch that", "no wait", "i mean", "actually", "no make it", "or rather", "wait no"]
selfcorr = list(SELFCORR_AUTH)
_seen = {r for r, _ in selfcorr}
for _ in range(70):
    (al, aw), pairs = RNG.choice(SC_GROUPS)
    a, b, B = RNG.choice(pairs)
    m = RNG.choice(SC_MARK)
    raw = f"{al} {a} {m} {b}" if RNG.random() < 0.5 else f"{al} {a} {m} {al} {b}"
    if raw in _seen:
        continue
    _seen.add(raw)
    selfcorr.append((raw, f"{aw} {B}."))

# CONFLICT-RESOLVER: one utterance with BOTH a self-correction AND profanity ->
# collapse the correction but KEEP the profanity. This is the exact case the v4
# 2B got wrong (collapse made it deletion-happy and it dropped the swear).
COLLAPSE_PROF = [
    ("send it monday scratch that tuesday this is so fucking late", "Send it Tuesday. This is so fucking late."),
    ("the total is fifty bucks i mean fifteen goddamn dollars", "The total is fifteen goddamn dollars."),
    ("call sarah no wait call mike this is such bullshit", "Call Mike. This is such bullshit."),
    ("meet at noon no make it one im so damn busy", "Meet at one. I'm so damn busy."),
    ("we need ten units scratch that twenty the client is being an asshole", "We need twenty units. The client is being an asshole."),
    ("turn left actually turn right this fucking gps is wrong", "Turn right. This fucking GPS is wrong."),
    ("ship it to chicago no denver the shit got delayed again", "Ship it to Denver. The shit got delayed again."),
    ("the deadline is friday scratch that thursday and im so fucking stressed", "The deadline is Thursday and I'm so fucking stressed."),
    ("book a table for four no wait six this place is a goddamn nightmare to get into", "Book a table for six. This place is a goddamn nightmare to get into."),
    ("set it to twenty no make it twenty two its hot as hell in here", "Set it to twenty-two. It's hot as hell in here."),
    ("invite ten people i mean fifteen this party is gonna be a shit show", "Invite fifteen people. This party is gonna be a shit show."),
    ("color it blue no green the damn logo looks off either way", "Color it green. The damn logo looks off either way."),
    ("the flight is at six no wait seven this whole trip is fucked", "The flight is at seven. This whole trip is fucked."),
    ("email it to sarah actually email it to me im so done with this bullshit", "Email it to me. I'm so done with this bullshit."),
    ("we leave at eight no nine the traffic is gonna be hell", "We leave at nine. The traffic is gonna be hell."),
    ("the password is admin no its root god this is a damn mess", "The password is root. God, this is a damn mess."),
    ("park on the left scratch that the right that asshole took my spot", "Park on the right. That asshole took my spot."),
    ("its on the second floor wait the third this building is a fucking maze", "It's on the third floor. This building is a fucking maze."),
    ("reserve it under smith no jones the system is being a piece of shit", "Reserve it under Jones. The system is being a piece of shit."),
    ("we need it by friday or rather thursday and im pissed about it", "We need it by Thursday and I'm pissed about it."),
    ("the budget is fifty grand i mean sixty and its still not enough damn it", "The budget is sixty grand and it's still not enough, damn it."),
    ("call me at three no four this client is such a pain in the ass", "Call me at four. This client is such a pain in the ass."),
    ("use the blue template actually the red one the old one looks like crap", "Use the red template. The old one looks like crap."),
    ("the meeting is in room 205 scratch that 210 down the goddamn hall", "The meeting is in room 210, down the goddamn hall."),
    ("send the report to john no the whole team this is fucking urgent", "Send the report to the whole team. This is fucking urgent."),
]
selfcorr += COLLAPSE_PROF

# --------------------------------------------------------------- assemble
def to_record(raw, clean, style):
    return {"messages": [
        {"role": "system", "content": cleanup_prompt(style)},
        {"role": "user", "content": WRAP.format(raw=raw)},
        {"role": "assistant", "content": clean},
    ], "style": style, "teacher": "claude-opus-4-8 (synthetic)"}

def load_jsonl(p):
    p = HERE / "data" / p
    return [json.loads(l) for l in p.open()] if p.exists() else []

# new synthetic verbatim (corruption) — multiple corruptions per clean
new_verb = [to_record(r, c, "verbatim") for r, c, _ in verbatim_pairs(CLEANS, per=3)]
# v4 shared-verbatim additions -> ALL tiers (foreign passthrough, anti-ellipsis,
# mid-phrase repetition collapse, verbatim reinforcement)
new_verb += [to_record(r, c, "verbatim") for r, c in
             foreign_pairs + ANTI_ELLIPSIS + REPETITION + reinforce_pairs + profanity_pairs]
# authored weak-spot verbatim (the 228) — already verbatim records
authored = [r for r in load_jsonl("trainset_weakness.jsonl")]
# existing Grok data, split by style
grok = load_jsonl("train_v3.jsonl")    # 1470 verbatim+tidy (Grok+authored)
grok_verb = [r for r in grok if r.get("style") == "verbatim"]
grok_tidy = [r for r in grok if r.get("style") == "tidy"]
grok_fmt = load_jsonl("formatted_all.jsonl")   # 594 formatted

new_tidy = [to_record(r, c, "tidy") for r, c in TIDY + tidy_synth]
new_fmt = [to_record(r, c, "formatted") for r, c in FORMATTED + fmt_synth + enterprise_fmt]

def dedup(rows):
    seen, out = set(), []
    for r in rows:
        k = (r["style"], r["messages"][1]["content"])
        if k in seen: continue
        seen.add(k); out.append(r)
    RNG.shuffle(out)
    return out

verbatim_all = dedup(new_verb + authored + grok_verb)         # everything verbatim
tidy_all = dedup(new_tidy + grok_tidy)                         # everything tidy
formatted_all = dedup(new_fmt + grok_fmt)                      # everything formatted

# v4 tier-EXCLUSIVE pools (style=verbatim; placement enforces the tier-blocking)
v4_08b = [to_record(r, c, "verbatim") for r, c in email_leave_pairs + linebreak_pairs]  # 0.8B: leave symbols for the scaffold
v4_conv = [to_record(r, c, "verbatim") for r, c in email_conv + url_conv]               # 2B/4B: CONVERT emails/urls
v4_selfcorr = [to_record(r, c, "verbatim") for r, c in selfcorr]                         # 2B/4B: collapse marked self-corrections
v4_4b = [to_record(r, c, "verbatim") for r, c in HARD_EMAIL]                             # 4B: hard email forms

files = {
    "train_0.8b.jsonl": dedup(verbatim_all + v4_08b),
    "train_2b.jsonl": dedup(verbatim_all + tidy_all + v4_conv + v4_selfcorr),
    "train_4b.jsonl": dedup(verbatim_all + tidy_all + formatted_all + v4_conv + v4_selfcorr + v4_4b),
}
for name, rows in files.items():
    with (HERE / "data" / name).open("w") as f:
        for r in rows:
            f.write(json.dumps(r) + "\n")
    import collections
    mix = collections.Counter(r["style"] for r in rows)
    print(f"{name:18} {len(rows):5} pairs   {dict(mix)}")
print(f"\npools: verbatim={len(verbatim_all)} tidy={len(tidy_all)} formatted={len(formatted_all)}")
